name: Run Behave Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psutil
          pip install allure-behave

      - name: Install Allure Command-Line Tool
        run: |
          npm install -g allure-commandline --save-dev

      - name: Run Behave tests
        run: |
          behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results features

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      - name: Generate Allure Report
        run: |
          allure generate reports/allure-results --clean -o reports/allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write  # Grants permission to push changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/allure-report
